### ISSUE TITLE
Where can I find the pinout?

### ISSUE THREAD

**Issue by clahil-linum** [sparkfun/SparkFun_GPS_Dead_Reckoning_PHat_ZED-F9R#1]
### Subject of the issue

I try to figure out which pins of the ZED-F9R are connected to which pins of the Raspberry pHAT? I searched the Wiki, try to find something with Google but nothing comes up. I'm especially interessted in the geofence pin.

The only information I found is that the pHat uses the UART from this video: https://www.youtube.com/watch?v=ITBoPNNsycY

**Comment by bboyho** [comment]
Hi!

I just noticed this question when updating the GitHub repo. The YouTube video is just the SparkFun product showcase.

For more information, you will want to check the product page or [tutorial](https://learn.sparkfun.com/tutorials/sparkfun-gps-rtk-dead-reckoning-zed-f9r-hookup-guide/hardware-overview-phat). The [pHAT's Eagle design files](https://learn.sparkfun.com/tutorials/sparkfun-gps-rtk-dead-reckoning-zed-f9r-hookup-guide/resources-and-going-further) will show what is connected to the Raspberry Pi's 2x20 GPIO pins. Of course, the schematic will be easier to see but you can highlight the board's traces with the board file. 

If you are still wondering, the Geofence pin from the ZED-F9R connects to an LED and it will turn on when the module is configured for geofencing. Looking at the Python Package, it doesn't look like there is an example like the Arduino Library. I haven't tried this feature yet, but you will probably want to configure the module with the u-blox software and then manually wire the pin to a Pi's GPIO before being able to read when the geofence net is high or low.
